### ISSUE TITLE
We should early fail if a content is not anymore in the library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-hotspot#571]
Not having a content anymore in the library (so removed after Kiwix Hotpost configuration) is a legitimate use case. If this happens it should generate an error earlier. This is differrent than not being able to download a ZIM file (which sounds more like an error).

**Comment by rgaudin** [comment]
It's already the case. A zim *that is not anymore in the library* is a strictly the same as a Zim that has never been in the library and we don't allow that.

What might happen is that due to the double library currently in place, we might be off-sync by up to 24h. So if a Zim got removed from main library, it might still be in hotspot library and will thus not fail immediatly on startup…

But it will still fail *somewhat early* during download which happens at the beginning of the process.

So I'm closing this as awaiting OPDS switch.
