### ISSUE TITLE
Relocate master images

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-hotspot#576]
Current master images are available at https://download.kiwix.org/hotspots/. This directory will disappear as our plan is to store kiwix hotspot images in S3. But we still need to provide the base image, probably in download.kiwix.org. I would propose to relocated the master images in the respective kiwix-hotspot releases dedicated directory.

**Comment by rgaudin** [comment]
As discussed, master images to be relocated from `/hotspots/base/` to `/release/kiwix-hotspot/master-images`.

I have already moved latest image to `/release/kiwix-hotspot/master-images/2021-04-20/`. I think we should only move the previous one which we've been using since version `2.1.0` on  Aug 21, 2019.

@kelson42 please create a redirection from `/hotspots/base/hotspot-master_2019-08-24.img.zip` to `/release/kiwix-hotspot/master-images/2019-08-24/hotspot-master_2019-08-24.img.zip` (file already exists) and remove the whole base folder if you wish to.

**Comment by kelson42** [comment]
I have put new images at https://download.kiwix.org/release/kiwix-hotspot/master/

**Comment by rgaudin** [comment]
I see redirections are OK ; Should we close?

**Comment by kelson42** [comment]
@rgaudin AFAIK:
* Redirections are not OK at all (I don't have made anything)
* Kiwix-hotspot CI is not fixed to upload at the right place

**Comment by rgaudin** [comment]
Ah so you left both files?

**Comment by kelson42** [comment]
@rgaudin I let you fix the CI. When it is done, we can remove the old files from download.kiwix.org

**Comment by kelson42** [comment]
And fix “hostpot”

**Comment by rgaudin** [comment]
> And fix “hostpot”

This doesn't need to be fixed. The workflow generating it has the right name. the typo was introduced by manual manipulations.

https://github.com/kiwix/kiwix-hotspot/blob/master/.github/workflows/create-master.yml

**Comment by kelson42** [comment]
Why I have seen 3 typos in the code then?

**Comment by rgaudin** [comment]
Because the code (japon) uses this manually edited master.

Next master won't have the typo ans selecting a master to use is a matter of copy-pasting its file name and metadata in the json file.
